export const SONG_LIST_REQUEST= 'SONG_LIST_REQUEST'
export const SONG_LIST_SUCCESS= 'SONG_LIST_SUCCESS'
export const SONG_LIST_FAIL= 'SONG_LIST_FAIL'

export const SONG_CURRENT_PLAY_REQUEST= 'SONG_CURRENT_PLAY_REQUEST'
export const SONG_CURRENT_PLAY_SUCCESS= 'SONG_CURRENT_PLAY_SUCCESS'
export const SONG_CURRENT_PLAY_FAIL= 'SONG_CURRENT_PLAY_FAIL'

export const SONG_CURRENT_DETAILS_REQUEST= 'SONG_CURRENT_DETAILS_REQUEST'
export const SONG_CURRENT_DETAILS_SUCCESS= 'SONG_CURRENT_DETAILS_SUCCESS'
export const SONG_CURRENT_DETAILS_FAIL= 'SONG_CURRENT_DETAILS_FAIL'